<?php
/*
Autor:Fernando
Date:20/04/2005
*/
require_once("../../config.php");
echo $html_header;
?>
<body>

<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; text-decoration: underline; text-transform: none; font-variant:normal; ">TEOR�?A DE LA INFORMACIÓN</span></p>
<p class="Normal" style="text-align:center; font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; text-transform: none; font-variant:normal; ">INFORME de PROYECTO:</span></p>
<p class="Normal" style="text-align:center; font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; text-decoration: underline; ">FIRMAS DIGITALES</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-weight: bold; font-size: 24pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-weight: bold; font-size: 24pt; "><span style="font-family: 'Sans Serif'; font-weight: normal; text-transform: none; font-variant:normal; ">Descripci�n del programa JCripto10 (cifrador)</span></p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:right; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; text-decoration: underline; text-transform: none; font-variant:normal; ">Grupo de trabajo:</span></p>
<p class="Normal" style="text-align:right; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">Gaudina, Gabriel</span></p>
<p class="Normal" style="text-align:right; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">Tripicchio, Fernando</span></p>
<p class="Normal" style="text-align:right; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">Sanchez, Eduardo</span></p>
<p class="Normal" style="text-align:right; font-family: 'Sans Serif'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:right; font-family: 'Sans Serif'; font-size: 11pt; ">&nbsp;</p><hr>
<p class="Normal" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-weight: bold; font-size: 12pt; text-decoration: underline; text-transform: none; font-variant:normal; ">�?ndice de contenido</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Standard" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-decoration: underline; text-transform: none; font-variant:normal; ">Tema									Página</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">Comentarios previos sobre el cifrador					3</span></p>
<p class="Normal" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">Fundamentos teóricos del cifrador						4</span></p>
<p class="Normal" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">Funciones del cifrador							6</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">	Generación de claves							6</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">	Cifrado de un archivo							6</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">	Descifrado de un archivo						6</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">	Firmado de un archivo						7</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">	Verificación de la firma						7</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">	Compresión de archivos						7</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">	Descompresión de archivos						7</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">	Comparación de archivos						7</span></p>
<p class="Standard" style="line-height:200%; font-family: 'Sans Serif'; ">Conclusión									8</p>
<p class="Standard" style="line-height:200%; font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p><hr>
<p class="Standard" style="text-align:center; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-weight: bold; font-size: 12pt; text-decoration: underline; text-transform: none; font-variant:normal; ">Comentarios previos sobre el cifrador</span></p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-style: italic; font-size: 11pt; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-style: italic; font-size: 11pt; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; line-height:150%; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-style: italic; font-size: 12pt; text-transform: none; font-variant:normal; ">El cifrador fue programado utilizando el lenguaje Java en su versión 1.5.0_03 (Sun JDK1.5.0_03). Esto debe ser tenido en cuenta a la hora de la instalacíon de la máquina virtual (jvm) para la ejecución del programa, se recomienda el uso de Sun Java JRE 1.5.X_XX (o superior), ya que no garantizamos el buen funcionamiento del cifrador con otra máquina virtual que no sean las mencionadas (como en el caso de msjvm – MicroSoft Java Virtual Machine -  o Sun JRE 1.4.X 1.3.X o 1.2.X), aunque en el caso particular de Sun JRE 1.4.3_08 el programa funciona correctamente al menos con los tipos de archivos mas utilizados (exe, doc, txt, zip, jpg, jar). </span></p>
<p class="Standard" style="text-align:justify; line-height:150%; font-family: 'Sans Serif'; font-style: italic; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; line-height:150%; font-family: 'Sans Serif'; font-style: italic; ">¿Por qué Java?</p>
<p class="Standard" style="text-align:justify; line-height:150%; font-family: 'Sans Serif'; font-style: italic; ">Porque por su potencia (estructuras implementadas), seguridad (implementada a traves del paradigma de objetos) y sobre todo independencia de plataforma (no nos obliga al uso de una arquitectura o sistema operativo), nos permite integrarlo en otras herramientas (como por ejemplo PHP) sin preocuparnos del servidor que lo ejecute y brindarle una interfaz mas amigable que la &quot;línea de comandos&quot; al usuario.</p>
<p class="Standard" style="text-align:justify; line-height:150%; font-family: 'Sans Serif'; font-style: italic; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; line-height:150%; font-family: 'Sans Serif'; font-style: italic; ">¿Por qué un método de cifrado nuevo?</p>
<p class="Standard" style="text-align:justify; line-height:150%; font-family: 'Sans Serif'; font-style: italic; ">Porque crear un método nuevo nos permitió ver cómo funciona todo el proceso de cifrado, y enfrentarnos a problemas de &quot;seguridad&quot; debido a fallas en el diseño para perfeccionarlo hasta el punto actual.</p>
<p class="Standard" style="text-align:justify; line-height:150%; font-family: 'Sans Serif'; font-style: italic; ">&nbsp;</p><hr>
<p class="Standard" style="text-align:center; line-height:150%; font-family: 'Sans Serif'; font-style: italic; "><span style="font-style: normal; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Fundamentos</span><span style="font-style: normal; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">&nbsp;</span><span style="font-style: normal; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">teóricos</span><span style="font-style: normal; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">&nbsp;</span><span style="font-style: normal; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">del</span><span style="font-style: normal; font-weight: bold; text-decoration: underline; 
text-transform: none; font-variant:normal; ">&nbsp;</span><span style="font-style: normal; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">cifrador</span></p>
<p class="Normal" style="font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">El cifrador presentado se basa en la función polinómica cúbica x</span><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; "><sup>2</sup></span><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">(b-x) y su representación gráfica es la siguiente:</span></p>
<p class="Illustration" style="text-align:center; "><span style="font-family: 'Sans Serif'; font-style: normal; text-transform: none; font-variant:normal; "><img src="./funciong.jpg"><br> Ilustración</span><span style="font-family: 'Sans Serif'; font-style: normal; text-transform: none; font-variant:normal; ">  </span><span style="font-family: 'Sans Serif'; font-style: normal; text-transform: none; font-variant:normal; ">Función</span><span style="font-family: 'Sans Serif'; font-style: normal; text-transform: none; font-variant:normal; "> f(x)=x*x*(b-x)</span></p>
<p class="Normal" style="font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">Elegimos esta función debido a las siguientes particularidades:</span></p>
<p class="Normal" style="text-align:justify; font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">El rango es limitado y parametrizado por el valor de &quot;b&quot; (y determina un máximo=2b/3).</span></p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">Dado un valor para &quot;x1&quot; y calculando el correspondiente &quot;f(x1)&quot; se puede aproximar el correspondiente valor de &quot;x2&quot; (f(x1)=f(x2)), la exactitud de la aproximación depende del rango utilizado y fijado por el valor de &quot;b&quot;. </span></p>
<p class="Normal" style="font-family: 'Luxi Sans'; font-size: 11pt; ">&nbsp;</p>
<p class="Normal" style="font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">En consecuencia, esta función nos permite, dando un valor a &quot;b&quot;, asignar aleatoriamente un valor a &quot;x1&quot;, en base al cual aproximar, a través de &quot;f(x1)&quot;, el valor de &quot;x2&quot; (f(x2)=f(x1)+E, donde E=f(x1)-f(x2) el error en la aproximación) y así obtener dos &quot;claves&quot; (o mejor dicho, partes de claves) correspondientes una a la otra y permitir que el cifrado sea reversible. </span></p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">Desde un punto de vista práctico, se puede dar a &quot;b&quot; un valor de un orden superior a, por ejemplo, 5000 bits (el número binario formado por un 1 seguido de 4999 ceros, es decir 2</span><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; "><sup>5000 </sup></span><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">= 1.412467032139426e+1505), el máximo estaría ubicado en 2(2</span><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; "><sup>5000</sup></span><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; 
font-variant:normal; ">)/3 = 9.4164468809295069e+1504, dando un conjunto de 4.7082234404647535e+1504 números entre los que elegir &quot;x1&quot;. </span></p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">Si bien no hemos demostrado con fundamentos matemáticos firmes la seguridad del método implementado, sin duda el punto más fuerte que éste tiene es el tiempo computacional que insumiría &quot;adivinar&quot; el par de claves usados en todo el proceso del firmado digital (el &quot;adivinar&quot; las claves utilizando &quot;fuerza bruta&quot; implicaría generar un valor para &quot;x1&quot;, obtener un valor para &quot;x2&quot; y así calcular el error E y tratar de descifrar un archivo).</p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">Para el ejemplo suponemos lo siguiente:</p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-style: italic; font-size: 12pt; text-transform: none; font-variant:normal; ">El hacker ha decompilado el programa y sabe qué combinación de variables debe usar para cifrar-descifrar un archivo, conoce la función que las genera y sabe cómo armar los archivos que contienen las claves que el programa usa (sin embargo, NO conoce la estructura de un archivo cifrado).</span></p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-style: italic; font-size: 12pt; text-transform: none; font-variant:normal; ">Que del rango &quot;[máximo, b]&quot; descarte valores &quot;poco probables&quot;, reduciendo el conjunto a, digamos, 1/1000 del total (es decir 4.7082234404647535e+1501 valores) lo cual es bastante pesimista para nosotros!</span></p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-style: italic; font-size: 12pt; text-transform: none; font-variant:normal; ">Que posea un poder de cálculo que le permita efectuar todos los pasos del &quot;cracking&quot; 1000000000000000000 (1 trillón) de veces por segundo.</span></p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; font-style: italic; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Luxi Sans'; font-size: 11pt; "><span style="font-family: 'Sans Serif'; font-size: 12pt; text-transform: none; font-variant:normal; ">En base a lo dicho, le tomaría unos 1.4929678591022176e+1473 MILENIOS!!!! &quot;adivinar&quot; las claves, mientras que para al programa le toma de uno a dos minutos en una computadora con un poder de cálculo mediano (PC hogareña) generar las claves de 5000 bits.</span></p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; ">&nbsp;</p><hr>
<p class="Standard" style="text-align:center; font-family: 'Sans Serif'; font-weight: bold; font-size: 24pt; "><span style="font-weight: normal; font-size: 12pt; text-decoration: underline; text-transform: none; font-variant:normal; "><b>Funciones</span><span style="font-weight: normal; font-size: 12pt; text-decoration: underline; text-transform: none; font-variant:normal; ">&nbsp;</span><span style="font-weight: normal; font-size: 12pt; text-decoration: underline; text-transform: none; font-variant:normal; ">del</span><span style="font-weight: normal; font-size: 12pt; text-decoration: underline; text-transform: none; font-variant:normal; ">&nbsp;</span><span style="font-weight: normal; font-size: 12pt; text-decoration: underline; text-transform: none; font-variant:normal; ">cifrador</span></b></p>
<p class="Standard">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">El cifrador cuenta con varias funcionalidades. Además de la generación de claves, cifrado, descifrado y firmado, puede también verificar las firmas, comprimir y descomprimir los archivos que se envían/reciben. Estas funcionalidades se detallan a continuación:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Sans Serif'; ">*<span style="font-style: italic; text-transform: none; font-variant:normal; ">tener en cuenta que a los comandos abajo comentados se debe anteponer &quot;</span><span style="font-style: italic; font-weight: bold; text-transform: none; font-variant:normal; ">java -jar</span><span style="font-style: italic; text-transform: none; font-variant:normal; "> ...&quot; para poder ejecutarlos.</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Generación de claves:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: Monospace; font-style: italic; text-transform: none; font-variant:normal; ">jcripto -g &lt;cantidad de dígitos&gt; &lt;nombre de archivo de las claves&gt;</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">Este comando le indica al cifrador que debe generar una clave pública y una privada de longitud igual a &lt;cantidad de dígitos&gt; (en realidad, el programa si bien genera claves de &lt;cantidad de dígitos&gt; de longitud, utiliza números de &lt;cantidad de dígitos&gt; x3, para compensar el descarte de dígitos producto de la aproximación de los parámetros mencionados mas arriba – f(x1) y f(x2)). Luego de generar dichas claves, el programa las almacena cada una en un archivo: “&lt;nombre de archivo de las claves&gt;.pri�? y “&lt;nombre de archivo de las claves&gt;.pub�? (clave privada y pública respectivamente).</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Cifrado de un archivo:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: Monospace; font-style: italic; text-transform: none; font-variant:normal; ">jcripto -c &lt;archivo a cifrar&gt; &lt;clave a utilizar&gt;</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">En este caso se le indica al cifrador que tome el archivo &lt;archivo a cifrar&gt; y el archivo de clave &lt;clave a utilizar&gt; (un archivo de extensión “pri�? o “pub�?, según se desee cifrar con la clave privada del remitente o con la clave pública del destinatario). Para tal fin se utiliza un método bastante simple (al menos en esta versión del programa) que consiste en “leer�? el archivo &lt;archivo a cifrar&gt; en bloques de bytes de igual tamaño que la clave usada y contenida en &lt;clave a utilizar&gt;, aplicar entre ellos una operación lógica de XOR (hemos elegido ésta por ser reversible y por lo mismo asegurar la igualdad a nivel de bits del archivo original sin cifrar con el archivo descifrado), y “escribir�? el bloque resultante en un archivo de salida llamado “&lt;archivo a cifrar&gt;.cif�?</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Descifrado de un archivo:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: Monospace; font-style: italic; text-transform: none; font-variant:normal; ">jcripto -d &lt;archivo cifrado&gt; &lt;clave a utilizar&gt;</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">Con estos parámetros el programa utiliza la clave “&lt;clave a utilizar&gt;�? (un archivo .pri o .pub según corresponda) para descifrar el archivo “&lt;archivo cifrado&gt;�? (utilizando la misma operación que se utilizó para cifrarlo, XOR) y generando un archivo cuyo nombre es igual al del archivo “&lt;archivo cifrado&gt;�? pero sin la extensión “cif�?.</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Firmado de un archivo:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: Monospace; font-style: italic; text-transform: none; font-variant:normal; ">jcripto -f &lt;archivo&gt;</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">Esto realiza el firmado del archivo “&lt;archivo&gt;�? utilizando un método simple, con el cual se “lee�? el archivo en bloques fijos de “n�? bytes, y luego de suman estos bloques (tratándolos como números “grandes�?), el resultado se almacena en un archivo “&lt;archivo&gt;.hash�?. El método utilizado es lo suficientemente preciso como para obtener un “firmado�? distinto en caso de modificar incluso una letra en el archivo original.</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Verificado de una firma:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: Monospace; font-style: italic; text-transform: none; font-variant:normal; ">jcripto -v &lt;firma&gt; &lt;archivo descifrado&gt;</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">En este caso el programa compara (a nivel de bits) la firma provista “&lt;firma&gt;�? con la obtenida al realizar el “firmado�? del archivo descifrado “&lt;archivo descifrado&gt;�?, si coinciden se establece la legitimidad del archivo recibido.</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Compresión de los archivos que se enviarán:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: Monospace; font-style: italic; text-transform: none; font-variant:normal; ">jcripto -z &lt;archivo1&gt; &lt;archivo2&gt;</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">La intención de esta funcionalidad es la de comprimir (utilizando el algoritmo de Huffman -ZIP) el archivo cifrado y el que contiene la firma para que el envío por un medio digital (Internet, teléfono, etc.) sea menos costoso. El programa genera un archivo “zip�? cuyo nombre corresponde al del primer archivo pasado como parámetro.</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Descompresión de archivos recibidos:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: Monospace; font-style: italic; text-transform: none; font-variant:normal; ">jcripto -u &lt;archivo&gt;</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">Con esto el programa descomprime el archivo “&lt;archivo&gt;�? en los dos originalmente comprimidos.</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Comparado de dos archivos:</span></p>
<p class="Standard" style="font-family: 'Sans Serif'; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: Monospace; font-style: italic; text-transform: none; font-variant:normal; ">jcripto -cmp &lt;archivo1&gt; &lt;archivo2&gt;</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Luxi Sans'; "><span style="font-family: 'Sans Serif'; text-transform: none; font-variant:normal; ">Esta es una funcionalidad agregada con el solo propósito de verificación “manual�? del correcto funcionamiento del cifrado principalmente al procesar archivos con formatos nuevos o de tamaños considerables.</span></p>
<p class="Standard" style="font-family: 'Luxi Sans'; ">&nbsp;</p>
<p class="Standard" style="font-family: 'Sans Serif'; ">&nbsp;</p><hr>
<p class="Standard" style="text-align:center; font-family: 'Sans Serif'; "><span style="font-weight: bold; text-decoration: underline; text-transform: none; font-variant:normal; ">Conclusión</span></p>
<p class="Normal" style="text-align:center; font-family: Arial; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Normal" style="text-align:center; font-family: Arial; font-weight: bold; text-decoration: underline; ">&nbsp;</p>
<p class="Standard" style="text-align:justify; line-height:200%; font-family: 'Sans Serif'; ">La implementación del método descripto nos permitió entender el funcionamiento de todo el proceso de cifrado y firmado digital enfrentándonos a &quot;problemas reales&quot; en cuanto a seguridad dándonos una idea de lo que se busca en dicha área de la ciencia de la computación de una manera mas didáctica que simplemente implementar un método reconocido y en el que no hay algo para descubrir.</p>
